apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-project
  namespace: grafana-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-project
  template:
    metadata:
      labels:
        app: grafana-project
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
          - "10.12.0.2"
      containers:
      - name: grafana-bwg
        image: grafana/grafana:latest
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "2"
        ports:
        - name: grafana-port
          containerPort: 3000
        volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: pvc-grafana-project
      
