apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana-project
  namespace: grafana-space
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 189.19.99.96
    path: "/mnt/apps/grafana-vol"
