apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana-project
  namespace: grafana-space
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi